/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 building06112024.glb --keepnames 
*/

import { useGLTF, useHelper } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { useNavigate } from "react-router-dom";

const Lights = ({ color, distance, decay, intensity, x, y, z }) => {
  const ref = useRef();
  // const helper = useHelper(ref, THREE.PointLightHelper, 0.02, 'red');
  // const {color, distance, decay, intensity, x,y,z} = useControls({
  //   color: "#ffffff",
  //   distance: 3,
  //   decay: 2,
  //   intensity: 1,
  //   x: 0,
  //   y: 0,
  //   z: 0,

  // })

  return (
    <pointLight
      ref={ref}
      position={[x, y, z]}
      intensity={intensity}
      distance={distance}
      decay={decay}
      color={color}
    />
  );
};

// color: "#069a09",
// distance: 22.7,
// decay: 2.6,
// intensity: 100,
// x: 0,
// y: 0.05,
// z: -0.01,

// color: "#bf2400",
// distance: 25.7,
// decay: 2.4,
// intensity: 100,
// x: 0.10,
// y: 0.05,
// z: -0.01,

// color: "#069a09",
// distance: 25.7,
// decay: 2.4,
// intensity: 100,
// x: 0.24,
// y: 0.05,
// z: -0.01,

// color: "#997f06",
// distance: 25.7,
// decay: 2.4,
// intensity: 100,
// x: 0.14,
// y: 0.05,
// z: 0.09,

// color: "#069a09",
// distance: 25.7,
// decay: 2.4,
// intensity: 100,
// x: 0.14,
// y: 0.05,
// z: -0.11,

// color: "#997f06",
// distance: 25.7,
// decay: 2.4,
// intensity: 100,
// x: -0.04,
// y: 0.05,
// z: -0.11,

// color: "#997f06",
// distance: 25.7,
// decay: 2.4,
// intensity: 100,
// x: -0.04,
// y: 0.05,
// z: 0.11,

export default function Building4(props) {
  const { nodes, materials } = useGLTF("/building06112024.glb");

  const [hidden, setHidden] = useState(true);
  const navigate = useNavigate();

  const buildingClicked = () => {
    // setHidden(!hidden);
    navigate("/floor");
  };

  useEffect(() => {
    const homepageUrl = "http://localhost:5173/floor"; // Replace with your actual homepage URL
    if (window.location.href === homepageUrl) {
      setHidden(!hidden);
    }
  }, []);

  const resetHidden = () => {
    setHidden(false);
  };

  const stripe = useRef();
  const stripe2 = useRef();

  const light = useRef();

  useFrame((state) => {
    const t = (0.5 + Math.sin(state.clock.elapsedTime * 5)) / 22;
    stripe.current.color.setRGB(32, 11 + t * 22, 2 + t * 61);
    stripe2.current.color.setRGB(32, 11 + t * 22, 2 + t * 61);
  });

  return (
    <group {...props} dispose={null} on onClick={buildingClicked}>
      <group
        name="floor00g"
        position={[-16.984, 14.793, 10.846]}
        rotation={[0, 1.134, -Math.PI]}
        scale={-232.699}
        visible={!hidden}
      >
        <mesh
          name="Curve034"
          geometry={nodes.Curve034.geometry}
          material={materials["floor-wall"]}
        />
        <mesh
          name="Curve034_1"
          geometry={nodes.Curve034_1.geometry}
          material={materials["floor-glass"]}
        />
      </group>
      <group
        name="floor01"
        position={[-8.086, 24.939, -10.656]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={232.699}
        visible={!hidden}
      >
        <mesh
          name="Curve019"
          geometry={nodes.Curve019.geometry}
          material={materials["floor-wall"]}
        />
        <mesh
          name="Curve019_1"
          geometry={nodes.Curve019_1.geometry}
          material={materials["floor-glass"]}
        />
      </group>
      <group
        name="floor02"
        position={[-8.086, 33.88, -10.656]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={232.699}
        visible={!hidden}
      >
        <mesh
          name="Curve030"
          geometry={nodes.Curve030.geometry}
          material={materials["floor-wall"]}
        />
        <mesh
          name="Curve030_1"
          geometry={nodes.Curve030_1.geometry}
          material={materials["floor-glass"]}
        />
      </group>
      <group
        name="floor03"
        position={[-8.086, 42.357, -10.656]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={232.699}
        visible={!hidden}
      >
        <mesh
          name="Curve031"
          geometry={nodes.Curve031.geometry}
          material={materials["floor-wall"]}
        />
        <mesh
          name="Curve031_1"
          geometry={nodes.Curve031_1.geometry}
          material={materials["floor-glass"]}
        />
      </group>
      <group
        name="floor04"
        position={[-8.086, 50.922, -10.656]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={232.699}
        visible={!hidden}
      >
        {/* --------------------------------------------------------------------- lights ---------------------------------------------------------------------*/}

        <group transparent visible={!hidden}>
          <Lights
            x={-0.04}
            y={0.05}
            z={0.11}
            intensity={100}
            distance={25.7}
            decay={2.4}
            color={"green"}
          />

          <Lights
            x={-0.04}
            y={0.05}
            z={-0.08}
            intensity={30}
            distance={25.7}
            decay={2.4}
            color={"yellow"}
          />

          <Lights
            x={0.09}
            y={0.05}
            z={-0.11}
            intensity={80}
            distance={25.7}
            decay={2.4}
            color={"green"}
          />

          <Lights
            x={0.12}
            y={0.03}
            z={0.11}
            intensity={30}
            distance={25.7}
            decay={2.4}
            color={"yellow"}
          />

          <Lights
            x={-0.04}
            y={0.05}
            z={0.05}
            intensity={80}
            distance={25.7}
            decay={2.4}
            color={"red"}
          />

          <Lights
            x={0.04}
            y={0.05}
            z={0.05}
            intensity={80}
            distance={25.7}
            decay={2.4}
            color={"red"}
          />

          <Lights
            x={-0.15}
            y={0.05}
            z={0.04}
            intensity={130}
            distance={25.7}
            decay={2.4}
            color={"green"}
          />

          <Lights
            x={0.15}
            y={0.05}
            z={0.04}
            intensity={130}
            distance={25.7}
            decay={2.4}
            color={"green"}
          />

          <Lights
            x={0.24}
            y={0.05}
            z={0.01}
            intensity={130}
            distance={25.7}
            decay={2.4}
            color={"green"}
          />
        </group>

        <mesh
          name="Curve013"
          geometry={nodes.Curve013.geometry}
          material={materials["floor-wall"]}
        />
        <mesh
          name="Curve013_1"
          geometry={nodes.Curve013_1.geometry}
          material={materials["floor-glass"]}
        />
      </group>
      <group
        name="logo006"
        position={[25.162, 57.621, -1.862]}
        rotation={[0, 1.332, 0]}
        scale={117.876}
        visible={hidden}
      >
        <mesh
          name="Curve007"
          geometry={nodes.Curve007.geometry}
          material={materials.logo}
        />

        <mesh
          name="Curve007_1"
          geometry={nodes.Curve007_1.geometry}
          // material={materials.glow}
        >
          <meshBasicMaterial ref={stripe} toneMapped={false} />
        </mesh>
      </group>
      <group
        name="BezierCircle046"
        position={[-12.86, 22.556, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh027"
          geometry={nodes.Mesh027.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh027_1"
          geometry={nodes.Mesh027_1.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh027_2"
          geometry={nodes.Mesh027_2.geometry}
          material={materials.seam}
        />
        <mesh
          name="Mesh027_3"
          geometry={nodes.Mesh027_3.geometry}
          material={materials["mid-gray"]}
        />
      </group>
      <group
        name="BezierCircle047"
        position={[-12.86, 22.596, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh028"
          geometry={nodes.Mesh028.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh028_1"
          geometry={nodes.Mesh028_1.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh028_2"
          geometry={nodes.Mesh028_2.geometry}
          material={materials.black}
        />
      </group>
      <group
        name="BezierCircle048"
        position={[-12.86, 31.343, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh001"
          geometry={nodes.Mesh001.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh001_1"
          geometry={nodes.Mesh001_1.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh001_2"
          geometry={nodes.Mesh001_2.geometry}
          material={materials.seam}
        />
        <mesh
          name="Mesh001_3"
          geometry={nodes.Mesh001_3.geometry}
          material={materials["mid-gray"]}
        />
      </group>
      <group
        name="BezierCircle049"
        position={[-12.86, 31.383, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh002"
          geometry={nodes.Mesh002.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh002_1"
          geometry={nodes.Mesh002_1.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh002_2"
          geometry={nodes.Mesh002_2.geometry}
          material={materials.black}
        />
      </group>
      <group
        name="BezierCircle050"
        position={[-12.86, 40.129, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh003"
          geometry={nodes.Mesh003.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh003_1"
          geometry={nodes.Mesh003_1.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh003_2"
          geometry={nodes.Mesh003_2.geometry}
          material={materials.seam}
        />
        <mesh
          name="Mesh003_3"
          geometry={nodes.Mesh003_3.geometry}
          material={materials["mid-gray"]}
        />
      </group>
      <group
        name="BezierCircle051"
        position={[-12.86, 40.169, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh004"
          geometry={nodes.Mesh004.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh004_1"
          geometry={nodes.Mesh004_1.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh004_2"
          geometry={nodes.Mesh004_2.geometry}
          material={materials.black}
        />
      </group>
      <group
        name="BezierCircle052"
        position={[-12.86, 48.916, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
        visible={hidden}
      >
        <mesh
          name="Mesh005"
          geometry={nodes.Mesh005.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh005_1"
          geometry={nodes.Mesh005_1.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh005_2"
          geometry={nodes.Mesh005_2.geometry}
          material={materials.seam}
        />
        <mesh
          name="Mesh005_3"
          geometry={nodes.Mesh005_3.geometry}
          material={materials["mid-gray"]}
        />
      </group>
      <group
        name="BezierCircle053"
        position={[-11.999, 48.955, -1.962]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh006"
          geometry={nodes.Mesh006.geometry}
          material={materials.glass}
        />
        <mesh
          name="Mesh006_1"
          geometry={nodes.Mesh006_1.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh006_2"
          geometry={nodes.Mesh006_2.geometry}
          material={materials.black}
        />
      </group>
      <mesh
        name="BezierCircle054"
        geometry={nodes.BezierCircle054.geometry}
        material={materials.black}
        position={[-12.86, 56.511, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
        visible={hidden}
      />
      <group
        name="top"
        position={[-12.86, 56.785, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
        visible={hidden}
      >
        <mesh
          name="Mesh030"
          geometry={nodes.Mesh030.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh030_1"
          geometry={nodes.Mesh030_1.geometry}
          material={materials.seam}
        />
      </group>
      <group
        name="BezierCircle056"
        position={[-12.86, 13.763, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh031"
          geometry={nodes.Mesh031.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh031_1"
          geometry={nodes.Mesh031_1.geometry}
          material={materials.seam}
        />
      </group>
      <group
        name="BezierCircle057"
        position={[-34.97, 13.958, 47.251]}
        rotation={[0, 1.134, -Math.PI]}
        scale={-34.051}
      >
        <mesh
          name="Mesh032"
          geometry={nodes.Mesh032.geometry}
          material={materials["glass.001"]}
        />
        <mesh
          name="Mesh032_1"
          geometry={nodes.Mesh032_1.geometry}
          material={materials["wall.003"]}
        />
      </group>
      <group
        name="BezierCircle058"
        position={[-12.86, 14.676, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
      >
        <mesh
          name="Mesh033"
          geometry={nodes.Mesh033.geometry}
          material={materials["wall.001"]}
        />
        <mesh
          name="Mesh033_1"
          geometry={nodes.Mesh033_1.geometry}
          material={materials.glass}
        />
      </group>
      <mesh
        name="Circle012"
        geometry={nodes.Circle012.geometry}
        material={materials.chrome}
        position={[17.317, 15.149, -50.635]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={0.99}
      />
      <mesh
        name="Circle013"
        geometry={nodes.Circle013.geometry}
        material={materials.chrome}
        position={[6.255, 15.149, -55.794]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={0.99}
      />
      <mesh
        name="Circle014"
        geometry={nodes.Circle014.geometry}
        material={materials.chrome}
        position={[23.334, 15.149, -30.98]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={0.99}
      />
      <mesh
        name="Circle015"
        geometry={nodes.Circle015.geometry}
        material={materials.chrome}
        position={[-12.594, 15.149, -47.734]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={0.99}
      />
      <mesh
        name="BezierCircle059"
        geometry={nodes.BezierCircle059.geometry}
        material={materials["wall.003"]}
        position={[-12.86, 62.776, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={34.051}
        transparent
        opacity={0}
        visible={hidden}
      />
      <group
        name="ppl"
        position={[-9.625, 33.798, -6.976]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={[34.061, 33.615, 34.061]}
        visible={hidden}
      >
        <mesh
          name="Mesh035"
          geometry={nodes.Mesh035.geometry}
          material={materials["ppl-texture.001"]}
        />
        <mesh
          name="Mesh035_1"
          geometry={nodes.Mesh035_1.geometry}
          material={materials["ppl-texture.002"]}
        />
        <mesh
          name="Mesh035_2"
          geometry={nodes.Mesh035_2.geometry}
          material={materials["ppl-texture.003"]}
        />
        <mesh
          name="Mesh035_3"
          geometry={nodes.Mesh035_3.geometry}
          material={materials["ppl-texture.004"]}
        />
      </group>
      <mesh
        name="BezierCircle001"
        geometry={nodes.BezierCircle001.geometry}
        material={materials["wall.003"]}
        position={[-12.86, 18.202, -0.086]}
        rotation={[Math.PI, -1.134, Math.PI]}
        scale={35.282}
      />
      <group
        name="logo001"
        position={[-50.644, 57.621, 0.422]}
        rotation={[Math.PI, -1.328, Math.PI]}
        scale={117.876}
        visible={hidden}
      >
        <mesh
          name="Curve002"
          geometry={nodes.Curve002.geometry}
          material={materials.logo}
        />

        <mesh
          name="Curve002_1"
          geometry={nodes.Curve002_1.geometry}
          // material={materials.glow}
        >
          <meshBasicMaterial ref={stripe2} toneMapped={false} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/building06112024.glb");
