/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 diorama06112024.glb --transform --keepmaterials --resolution=2048 
Files: diorama06112024.glb [122.2MB] > C:\Users\FelipeOlguera\Desktop\00 glen_iot\gltf\gltf\diorama06112024-transformed.glb [2.03MB] (98%)
*/

import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";

import Building4 from "./Building4";
import { Selection } from "@react-three/postprocessing";

export default function Diorama({ landx, landz, gesture, noHand }) {
  const { nodes, materials } = useGLTF("/diorama06112024-transformed.glb");

  return (
    <>
      <motion.group
        dispose={null}
        // scale={12}
        position={[0, -30, 1]}
        initial={{ rotateX: 0, scale: 0 }}
        animate={{
          scale: Math.max(0.8, noHand ? 0.8 : -landz / 7),
          rotateY: -landx,
        }}
        transition={{ duration: 1, ease: "easeOut" }}
        exit={{
          scale: 0,
          transition: { duration: 0.5, ease: "easeInOut", delay: 0.3 },
        }}
      >
        {" "}
        <Selection>
          <Building4 gesture={gesture} />
        </Selection>
        <group
          position={[-23.652, 3.744, 179.988]}
          rotation={[0, -1.571, 0]}
          scale={22.084}
        >
          <mesh
            geometry={nodes.Plane020.geometry}
            material={materials.PaletteMaterial003}
          />
          <mesh
            geometry={nodes.Plane020_1.geometry}
            material={materials.PaletteMaterial004}
          />
          <mesh
            geometry={nodes.Plane020_2.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.Plane020_3.geometry}
            material={materials.PaletteMaterial002}
          />
        </group>
        <mesh
          geometry={nodes.building03.geometry}
          material={materials.PaletteMaterial005}
          position={[-743.026, 7.742, 86.294]}
          rotation={[0, -1.571, 0]}
          scale={14.834}
        />
        <group
          position={[-458.427, 9.801, 315.208]}
          rotation={[0, 1.571, 0]}
          scale={[2.95, 3.093, 3.093]}
        >
          <mesh
            geometry={nodes.Mesh044.geometry}
            material={materials.StoneTile}
          />
          <mesh
            geometry={nodes.Mesh044_1.geometry}
            material={materials.PaletteMaterial007}
          />
          <mesh
            geometry={nodes.Mesh044_2.geometry}
            material={materials.PaletteMaterial006}
          />
        </group>
        <group
          position={[-505.856, 22.416, -361.862]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[40.089, 20.015, 53.764]}
        >
          <mesh
            geometry={nodes.Cylinder019.geometry}
            material={materials["stripe.002"]}
          />
          <mesh
            geometry={nodes.Cylinder019_1.geometry}
            material={materials["gray.003"]}
          />
          <mesh
            geometry={nodes.Cylinder019_2.geometry}
            material={materials["dgray.002"]}
          />
          <mesh
            geometry={nodes.Cylinder019_3.geometry}
            material={materials["concrt.002"]}
          />
          <mesh
            geometry={nodes.Cylinder019_4.geometry}
            material={materials["glass.004"]}
          />
          <mesh
            geometry={nodes.Cylinder019_5.geometry}
            material={materials["window_text.002"]}
          />
          <mesh
            geometry={nodes.Cylinder019_6.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Cylinder019_7.geometry}
            material={materials["green.002"]}
          />
          <mesh
            geometry={nodes.Cylinder019_8.geometry}
            material={materials["roof.002"]}
          />
        </group>
        <mesh
          geometry={nodes.building_omantel_tube.geometry}
          material={materials["neon.002"]}
          position={[-505.856, 22.416, -361.862]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[40.089, 20.015, 53.764]}
        />
        <mesh
          geometry={nodes.top001.geometry}
          material={materials["Material.001"]}
          position={[-94.374, 44.448, -128.987]}
          rotation={[Math.PI, -0.364, Math.PI]}
          scale={34.051}
        />
      </motion.group>
    </>
  );
}

useGLTF.preload("/diorama06112024-transformed.glb");
